name: "Build Reactant_jll"

on:
  # push:
  #   branches:
  #   - main
  #   paths:
  #     - '.github/workflows/build-reactantjll.yml'
  #     - '**/BUILD'
  #     - '**/WORKSPACE'
  #     - '**/*.bzl'
  #     - 'patches/**'
  #     - 'src/**'
  #     - 'third_party/**'
  pull_request:
    branches:
    - main
    paths:
      - '.github/workflows/build-reactantjll.yml'
      - '**/BUILD'
      - '**/WORKSPACE'
      - '**/*.bzl'
      - 'patches/**'
      - 'src/**'
      - 'third_party/**'

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  get-reactant-commit:
    name: 'Get Reactant commit'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Get latest Reactant commit
        id: get-reactant-main
        shell: bash
        run: |
          REACTANT_MAIN="$(git ls-remote https://github.com/EnzymeAD/Reactant.jl.git main | awk '{print $1}')"
          echo "reactant_main=${REACTANT_MAIN}"
          echo "reactant_main=${REACTANT_MAIN}" >> "${GITHUB_OUTPUT}"
    outputs:
      reactant_main: ${{ steps.get-reactant-main.outputs.reactant_main }}

  build-jll:
    name: Build Reactant_jll
    if: github.event.pull_request.draft == false
    uses: EnzymeAD/ReactantBuilder/.github/workflows/build-reactant-reusable.yml@main
    needs: get-reactant-commit
    secrets: inherit
    with:
      reactantbuilder_ref: 'main'
      enzyme_jax_commit: ${{ github.sha }}
      # If you want to use a different commit than `main`, put here the sha256
      # hash, but it must always be a hash, can't use branch name here.
      # reactant_commit: ${{ needs.get-reactant-commit.outputs.reactant_main }}
      reactant_commit: a222e51cc58c44729f637ee3cb83586189177302
